chrome.identity.launchWebAuthFlow(
  {
    url: "YOUR_GOOGLE_AUTH_URL", // Generated by supabase.auth.signInWithOAuth
    interactive: true,
  },
  (redirectedTo) => {
    if (chrome.runtime.lastError) {
      console.error(chrome.runtime.lastError);
      return;
    }
    console.log("Redirect URL:", redirectedTo);
  }
);